(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ada-indent 1)
 '(auto-save-timeout 5)
 '(auto-save-visited-mode t)
 '(column-number-mode t)
 '(connection-local-criteria-alist
	 '(((:application tramp :machine "localhost")
			tramp-connection-local-darwin-ps-profile)
		 ((:application tramp :machine "IB-MKARANASHEV-M")
			tramp-connection-local-darwin-ps-profile)
		 ((:application tramp)
			tramp-connection-local-default-system-profile tramp-connection-local-default-shell-profile)
		 ((:application eshell)
			eshell-connection-default-profile)))
 '(connection-local-profile-alist
	 '((tramp-connection-local-darwin-ps-profile
			(tramp-process-attributes-ps-args "-acxww" "-o" "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state=abcde" "-o" "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args")
			(tramp-process-attributes-ps-format
			 (pid . number)
			 (euid . number)
			 (user . string)
			 (egid . number)
			 (comm . 52)
			 (state . 5)
			 (ppid . number)
			 (pgrp . number)
			 (sess . number)
			 (ttname . string)
			 (tpgid . number)
			 (minflt . number)
			 (majflt . number)
			 (time . tramp-ps-time)
			 (pri . number)
			 (nice . number)
			 (vsize . number)
			 (rss . number)
			 (etime . tramp-ps-time)
			 (pcpu . number)
			 (pmem . number)
			 (args)))
		 (tramp-connection-local-busybox-ps-profile
			(tramp-process-attributes-ps-args "-o" "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "stat=abcde" "-o" "ppid,pgid,tty,time,nice,etime,args")
			(tramp-process-attributes-ps-format
			 (pid . number)
			 (user . string)
			 (group . string)
			 (comm . 52)
			 (state . 5)
			 (ppid . number)
			 (pgrp . number)
			 (ttname . string)
			 (time . tramp-ps-time)
			 (nice . number)
			 (etime . tramp-ps-time)
			 (args)))
		 (tramp-connection-local-bsd-ps-profile
			(tramp-process-attributes-ps-args "-acxww" "-o" "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args")
			(tramp-process-attributes-ps-format
			 (pid . number)
			 (euid . number)
			 (user . string)
			 (egid . number)
			 (group . string)
			 (comm . 52)
			 (state . string)
			 (ppid . number)
			 (pgrp . number)
			 (sess . number)
			 (ttname . string)
			 (tpgid . number)
			 (minflt . number)
			 (majflt . number)
			 (time . tramp-ps-time)
			 (pri . number)
			 (nice . number)
			 (vsize . number)
			 (rss . number)
			 (etime . number)
			 (pcpu . number)
			 (pmem . number)
			 (args)))
		 (tramp-connection-local-default-shell-profile
			(shell-file-name . "/bin/sh")
			(shell-command-switch . "-c"))
		 (tramp-connection-local-default-system-profile
			(path-separator . ":")
			(null-device . "/dev/null"))
		 (eshell-connection-default-profile
			(eshell-path-env-list))))
 '(custom-enabled-themes '(eink))
 '(custom-safe-themes
	 '("d6d4e0512dcaae663f7bd304557d6bc8b78c576be5af9c0b62b8447fb79b5fde" "021321ae56a45794f43b41de09fb2bfca184e196666b7d7ff59ea97ec2114559" "a6473f7abf949f4a6a1a9cc0dd37ea2e35ba3cea65d3442b98d65c5c5c5cb8d7" "a3e99dbdaa138996bb0c9c806bc3c3c6b4fd61d6973b946d750b555af8b7555b" "f5b6be56c9de9fd8bdd42e0c05fecb002dedb8f48a5f00e769370e4517dde0e8" "4c56af497ddf0e30f65a7232a8ee21b3d62a8c332c6b268c81e9ea99b11da0d3" "c433c87bd4b64b8ba9890e8ed64597ea0f8eb0396f4c9a9e01bd20a04d15d358" default))
 '(default-frame-alist '((vertical-scroll-bars) (undecorated . t)))
 '(display-line-numbers-type 'relative)
 '(fill-column 80)
 '(global-display-line-numbers-mode t)
 '(inhibit-startup-screen t)
 '(initial-frame-alist '((vertical-scroll-bars) (fullscreen . maximized)))
 '(ns-alternate-modifier 'super)
 '(ns-command-modifier 'meta)
 '(ns-right-alternate-modifier 'none)
 '(org-export-backends '(ascii html md odt))
 '(org-log-done 'time)
 '(org-todo-keywords '((sequence "TODO" "IN PROGRESS" "|" "DONE")))
 '(package-selected-packages
	 '(sweeprolog org-bullets org-gcal evil-ledger ledger-mode company-ledger undo-fu rustic lsp-treemacs lsp-ui kotlin-mode lsp-mode fzf elpy persistent-scratch fuel password-store evil-org emacs-everywhere find-file-in-project erlang projectile eink-theme basic-theme zenburn-theme zenburn undo-tree magit slime perspective fill-column-indicator helm j-mode bind-key company dash goto-chg uniquify-files wisi exec-path-from-shell ada-ref-man company-emoji markdown-mode solarized-theme evil))
 '(python-shell-interpreter "python3")
 '(scroll-bar-mode nil)
 '(solarized-scale-org-headlines t)
 '(solarized-use-less-bold t)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(warning-suppress-log-types '((comp) (comp) (comp)))
 '(warning-suppress-types '((comp) (comp))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#fffff8" :foreground "#111111" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "Thin" :family "Iosevka SS04")))))
